[build]
  command = "npm run build" # Replace with your actual build command
  publish = "build" # Replace with your build directory

[build.environment]
  NODE_VERSION = "16"
  CI = "false"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200