backend:
  name: git-gateway
  branch: master # or the branch you use for deployment

media_folder: "public/assets/test" # Path to store images
public_folder: "/assets/test"      # Public URL for images

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects" # Where content will be stored in the repo
    create: true               # Allow new entries
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Project Image", widget: "image" }