backend:
  name: git-gateway
  branch: master

# media_folder: "public/assets" # Root folder for media files
# media_folder: "public/assets/{{slug}}/{{fields.subfolders.title}}/{{fields.subfolders.images.name}}"
media_folder: "public/assets/{{slug}}/{{fields.subfolders.title}}/{{fields.subfolders.images.name}}"
public_folder: "/assets"

collections:
  - name: "imageFolders"
    label: "Image Folders"
    folder: "content/images"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Page Name"
        widget: "string"
      - name: "subfolders"
        label: "Projects"
        widget: "list"
        fields:
          - name: "title"
            label: "Folder Name"
            widget: "string"
          - name: "images"
            label: "Images"
            widget: "list"
            fields:
              - name: "image"
                label: "Image File"
                widget: "image"
              - name: "name"
                label: "Image Name"
                widget: "string"
              - name: "subfolder"
                label: "Subfolder Name"
                widget: "hidden"
                default: "{{fields.title}}"  # Referencing the subfolder's title