backend:
  name: git-gateway
  branch: master # Adjust this to your repository's default branch

media_folder: "content/images" # Root folder for uploaded images
public_folder: "/images" # Public path for the images

collections:
  - name: "images"
    label: "Images"
    folder: "content/images"
    create: true # Allow creating new files
    format: "yml" # Each image represented as a Markdown or YAML file
    fields:
      - label: "Root Folder"
        name: "root_folder"
        widget: "object"
        fields:
          - label: "Subfolders"
            name: "subfolders"
            widget: "list"
            fields:
              - label: "Subfolder Name"
                name: "name"
                widget: "string"
              - label: "Subfolder Contents"
                name: "contents"
                widget: "list"
                fields:
                  - label: "Sub-Subfolder Name"
                    name: "name"
                    widget: "string"
                  - label: "Images"
                    name: "images"
                    widget: "list"
                    fields:
                      - label: "Image File"
                        name: "image_file"
                        widget: "image"
                        media_library:
                          config:
                            multiple: true
                      - label: "Image Name"
                        name: "image_name"
                        widget: "string"
                        hint: "Name will be used for the URL (e.g., example.com/folder/image_name.png)"