backend:
  name: git-gateway
  branch: master

media_folder: "public/assets" # Root folder for media files
public_folder: "/assets"      # Public URL for media

collections:
  - name: "imageFolders"
    label: "Image Folders"
    folder: "content/images"   # Root folder for all image categories
    create: true
    slug: "{{slug}}"           # Use folder name as the slug
    fields:
      - name: "title"
        label: "Page Name"
        widget: "string"       # Name of the project type
      - name: "subfolders"
        label: "Folder"
        widget: "list"         # List of project subfolders
        fields:
          - name: "title"
            label: "Folder Name"
            widget: "string"   # Name of the project
          - name: "images"
            label: "Images"
            widget: "list"     # List of images for this project
            fields:
              - name: "image"
                label: "Image File"
                widget: "image" # Upload image