backend:
  name: git-gateway
  branch: master

# media_folder: "public/assets" # Root folder for media files
# media_folder: "public/assets/{{slug}}/{{fields.subfolders.title}}/{{fields.subfolders.images.name}}"
media_folder: "public/assets/{{slug}}/{{subfolder}}/{{name}}"
public_folder: "/assets"      # Public URL for media

collections:
  - name: "imageFolders"
    label: "Image Folders"
    folder: "content/images"   # Root folder for all image categories
    create: true
    slug: "{{slug}}"           # Use folder name as the slug
    fields:
      - name: "title"
        label: "Page Name"
        widget: "string"       # Name of the project type
      # - name: "subfolders"
      #   label: "Projects"
      #   widget: "list"         # List of project subfolders
      #   fields:
      #     - name: "title"
      #       label: "Project Name"
      #       widget: "string"   # Name of the project
      #     - name: "images"
      #       label: "Images"
      #       widget: "list"     # List of images for this project
      #       fields:
      #         - name: "image"
      #           label: "Image File"
      #           widget: "image" # Upload image
      #         - name: "name"
      #           label: "Image Name"
      #           widget: "string" # Name for the image (excluding extension)
      #           hint: "Provide a name for the image. The file extension will be added automatically."
      - name: "subfolders"
        label: "Projects"
        widget: "list"
        fields:
          - name: "title"
            label: "Folder Name"
            widget: "string"
          - name: "images"
            label: "Images"
            widget: "list"
            fields:
              - name: "image"
                label: "Image File"
                widget: "image"
              - name: "name"
                label: "Image Name"
                widget: "string"
              - name: "subfolder"
                label: "Subfolder Name"
                widget: "hidden"
                default: "{{title}}"